'use strict';
const M=Mahjong,$=id=>document.getElementById(id),key='hongzhong-family-v1';
const fresh=()=>({hand:Array(28).fill(0),melds:[],names:['东','南','西','北'],rounds:[]});let state=fresh();
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&!M.validate(saved.hand,saved.melds)&&saved.names?.length===4&&saved.names.every(n=>typeof n==='string')&&Array.isArray(saved.rounds)&&saved.rounds.every(r=>r.length===4&&r.every(Number.isSafeInteger)&&r.reduce((a,b)=>a+b,0)===0))state=saved;}catch{}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));}catch{$('storage-status').textContent='浏览器未允许保存；当前记录仅在本次页面停留中保留。';}}
function tile(t,click){const b=document.createElement('button');b.className='tile '+(t===27?'hong':['wan','tong','tiao'][Math.floor(t/9)]);b.type='button';b.textContent=t===27?'中':String(t%9+1);const s=document.createElement('small');s.textContent=t===27?'红中':['万','筒','条'][Math.floor(t/9)];b.append(s);b.setAttribute('aria-label',M.labels[t]+(click?'，点击移除':''));if(click)b.onclick=click;else {b.disabled=true;b.style.opacity=1;}return b;}
function draws(container,ts){const d=document.createElement('div');d.className='tiles';ts.forEach(t=>d.append(tile(t)));container.append(d);}
function renderHand(){const h=$('hand-tiles');h.replaceChildren();state.hand.forEach((n,t)=>{for(let i=0;i<n;i++)h.append(tile(t,()=>{state.hand[t]--;persist();renderHand();}));});if(!h.children.length)h.textContent='还没有牌，先录入手牌吧';const count=state.hand.reduce((a,b)=>a+b,0),ready=13-state.melds.length*3,full=ready+1;$('hand-count').textContent=`手牌 ${count} 张 · 副露 ${state.melds.length} 组 · 听牌需 ${ready} 张 / 摸牌后 ${full} 张`;
const result=$('analysis');result.replaceChildren();const strong=document.createElement('strong');result.append(strong);const err=M.validate(state.hand,state.melds);if(err)strong.textContent=err;else if(count===ready){const w=M.waits(state.hand,state.melds);strong.textContent=w.length?'已听牌 · 自摸以下牌可成胡':'当前未听牌';draws(result,w);}else if(count===full){strong.textContent=M.win(state.hand,state.melds)?'结构可胡 · 仅限自摸':'摸牌后手牌 · 暂未成胡';const options=M.discards(state.hand,state.melds);if(options.length){const p=document.createElement('p');p.textContent='可弃牌后听牌（不代表胜率排序）：';result.append(p);options.forEach(o=>{const p=document.createElement('p');p.textContent=`弃 ${M.labels[o.tile]} → 听 ${o.draws.map(t=>M.labels[t]).join('、')}`;result.append(p);});}else{const p=document.createElement('p');p.textContent='本次没有一弃即听的选择。';result.append(p);}}else strong.textContent=count<ready?`再录入 ${ready-count} 张查看听牌`:`请将手牌调整为 ${ready} 或 ${full} 张`;
const picker=$('picker');picker.replaceChildren();const total=[...state.hand];state.melds.flat().forEach(t=>total[t]++);for(let s=0;s<4;s++){const row=document.createElement('div');row.className='suit-row';for(let t=s*9;t<Math.min(s*9+9,28);t++){const b=tile(t);b.disabled=total[t]>=4||count>=full;b.style.opacity='';b.setAttribute('aria-label',`加入 ${M.labels[t]}，已用 ${total[t]} 张`);b.onclick=()=>{state.hand[t]++;persist();renderHand();};row.append(b);}picker.append(row);}
$('meld-count').textContent=`${state.melds.length} 组`;$('melds').replaceChildren();state.melds.forEach((m,i)=>{const d=document.createElement('div');d.className='meld-row';const s=document.createElement('span');s.textContent=m.map(t=>M.labels[t]).join(' ');const b=document.createElement('button');b.textContent='移除';b.className='quiet';b.onclick=()=>{state.melds.splice(i,1);persist();renderHand();};d.append(s,b);$('melds').append(d);});}
M.labels.forEach((label,t)=>{const o=document.createElement('option');o.value=t;o.textContent=label;$('meld-base').append(o);});
$('add-meld').onclick=()=>{const t=Number($('meld-base').value),type=$('meld-type').value;const m=type==='sequence'?[t,t+1,t+2]:Array(type==='kong'?4:3).fill(t);const melds=[...state.melds,m];const error=type==='sequence'&&(t>=27||t%9>6)?'顺子首张只能为一至七':M.validate(state.hand,melds);$('meld-error').textContent=error;if(!error){state.melds=melds;persist();renderHand();}};
$('clear-hand').onclick=()=>{state.hand=Array(28).fill(0);state.melds=[];persist();renderHand();};
function renderScore(){const scores=M.totals(state.rounds);$('round-count').textContent=`已记 ${state.rounds.length} 局`;$('players').replaceChildren();state.names.forEach((name,i)=>{const row=document.createElement('div');row.className='player';const n=document.createElement('input');n.value=name;n.maxLength=12;n.setAttribute('aria-label',`第 ${i+1} 位昵称`);n.onchange=()=>{state.names[i]=n.value.trim()||['东','南','西','北'][i];n.value=state.names[i];persist();};const p=document.createElement('span');p.className='points';p.textContent=scores[i]>0?'+'+scores[i]:scores[i];const d=document.createElement('input');d.type='number';d.step=1;d.placeholder='增减';d.id='delta-'+i;d.setAttribute('aria-label',`${name} 本局增减`);row.append(n,p,d);$('players').append(row);});$('undo-round').disabled=!state.rounds.length;$('history').replaceChildren();state.rounds.slice(-8).reverse().forEach((r,i)=>{const p=document.createElement('div');p.className='history-row';p.textContent=`第 ${state.rounds.length-i} 局：`+r.map((v,j)=>`${state.names[j]} ${v>0?'+':''}${v}`).join(' · ');$('history').append(p);});}
$('save-round').onclick=()=>{try{const d=state.names.map((_,i)=>{const v=$('delta-'+i).value.trim();if(v==='')throw Error('请填写四人的增减，未变化填 0');return Number(v);});const next=M.record(state.rounds,d);if(M.totals(next).some(v=>!Number.isSafeInteger(v)))throw Error('积分超出安全整数范围');state.rounds=next;persist();renderScore();$('score-error').textContent='本局已记录';}catch(e){$('score-error').textContent=e.message;}};
$('undo-round').onclick=()=>{state.rounds.pop();persist();renderScore();$('score-error').textContent='已撤销上一局';};
function secureRandom(){if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296;}return Math.random();}
$('roll').onclick=()=>{const d=M.dice(secureRandom);$('dice-result').textContent=d.map(n=>'⚀⚁⚂⚃⚄⚅'[n-1]).join(' ');$('dice-total').textContent=`${d[0]} + ${d[1]} = ${d[0]+d[1]} 点`;};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});['hand','score','dice'].forEach(id=>$(id).hidden=id!==b.dataset.tab);});
$('clear-all').onclick=()=>{if(!confirm('清空手牌、副露、昵称和所有积分记录？'))return;state=fresh();try{localStorage.removeItem(key);}catch{}renderHand();renderScore();$('score-error').textContent='';$('meld-error').textContent='';$('dice-result').textContent='⚀ ⚀';$('dice-total').textContent='合计 2 点';};
renderHand();renderScore();
// Expose the visible hand analysis where the browser supports WebMCP.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 try{Promise.resolve(document.modelContext.registerTool({
  name:'read_mahjong_hand_analysis',title:'读取当前手牌分析',
  description:'Read the hand and melds currently entered in the visible interface, with the same self-draw-only structural win, waiting-tile, and discard analysis. Does not change or upload any records.',
  inputSchema:{type:'object',properties:{},additionalProperties:false},
  annotations:{readOnlyHint:true,untrustedContentHint:false},
  execute(input){
   if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object');
   const hand=[...state.hand],melds=state.melds.map(m=>[...m]);
   return {hand,melds,labels:[...M.labels],validationError:M.validate(hand,melds),structuralSelfDrawWin:M.win(hand,melds),waitingTiles:M.waits(hand,melds),discardOptions:M.discards(hand,melds),rules:{redCenterWildcard:true,selfDrawOnly:true,sevenPairs:false}};
  }
 },{signal:lifecycle.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',e=>{if(!e.persisted)lifecycle.abort();},{once:true});
}
