'use strict';
const M=Mahjong,$=id=>document.getElementById(id),key='hongzhong-family-v1';
const fresh=()=>({hand:Array(28).fill(0),melds:[],drawnTile:null,replacementPending:false,claimDiscardPending:false,names:['东','南','西','北'],rounds:[]});let state=fresh();
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&!M.validate(saved.hand,saved.melds)&&saved.names?.length===4&&saved.names.every(n=>typeof n==='string')&&Array.isArray(saved.rounds)&&saved.rounds.every(M.validRound))state=saved;}catch{}
if(!Number.isInteger(state.drawnTile)||state.drawnTile<0||state.drawnTile>27||!state.hand[state.drawnTile]||state.hand.reduce((a,b)=>a+b,0)!==14-3*state.melds.length)state.drawnTile=null;
state.replacementPending=state.replacementPending===true&&state.hand.reduce((a,b)=>a+b,0)===13-3*state.melds.length&&state.melds.some(m=>m.length===4);
state.claimDiscardPending=state.claimDiscardPending===true&&!state.replacementPending&&state.hand.reduce((a,b)=>a+b,0)===14-3*state.melds.length&&state.melds.some(m=>m.length===3);
if(state.claimDiscardPending)state.drawnTile=null;
function persist(){try{localStorage.setItem(key,JSON.stringify(state));}catch{$('storage-status').textContent='浏览器未允许保存；当前记录仅在本次页面停留中保留。';}}
const handUndo=[];let handMode='';
function handPhase(hand=state.hand,melds=state.melds,pending=state.replacementPending){const count=hand.reduce((a,b)=>a+b,0),ready=13-3*melds.length,full=ready+1,error=M.validate(hand,melds);return {count,ready,full,error,stage:error||count>full?'correct':count<ready?'entry':count===ready?(pending?'replacement':'draw'):'discard'};}
function rememberHand(){handUndo.push({hand:[...state.hand],melds:state.melds.map(m=>[...m]),drawnTile:state.drawnTile,replacementPending:state.replacementPending===true,claimDiscardPending:state.claimDiscardPending===true});if(handUndo.length>50)handUndo.shift();}
function tile(t,click){const b=document.createElement('button');b.className='tile '+(t===27?'hong':['wan','tong','tiao'][Math.floor(t/9)]);b.type='button';b.dataset.tile=String(t);const img=document.createElement('img');img.src='tiles/'+t+'.svg';img.alt='';img.width=44;img.height=58;img.draggable=false;img.decoding='async';b.append(img);b.setAttribute('aria-label',M.labels[t]+(click?'，点击打出':''));if(click)b.onclick=click;else{b.disabled=true;}return b;}
function draws(container,ts){const d=document.createElement('div');d.className='tiles';ts.forEach(t=>d.append(tile(t)));container.append(d);}
function applyTileAction(kind,t){if(!Number.isInteger(t)||t<0||t>27)return false;const phase=handPhase();
 if(kind==='add'){const used=state.hand[t]+state.melds.flat().filter(x=>x===t).length;if(phase.error||phase.count>=phase.full||used>=4)return false;rememberHand();state.hand[t]++;state.drawnTile=['draw','replacement'].includes(phase.stage)?t:null;state.replacementPending=false;state.claimDiscardPending=false;handMode=(phase.stage==='replacement'?'杠后补摸 ':phase.stage==='draw'?'摸入 ':'加入 ')+M.labels[t];}
 else if(kind==='remove'){if(!state.hand[t]||phase.stage==='replacement')return false;rememberHand();state.hand[t]--;state.drawnTile=null;state.claimDiscardPending=false;handMode=(phase.stage==='discard'?'打出 ':'移除 ')+M.labels[t];}else return false;
 persist();renderHand();return true;
}
function planKong(type,t){
 const phase=handPhase();if(!Number.isInteger(t)||t<0||t>27)throw Error('请选择杠的牌');
 if(!['concealed','exposed','added'].includes(type))throw Error('请选择暗杠、明杠或补杠');
 if(phase.error)throw Error(phase.error);if(state.claimDiscardPending)throw Error('吃碰后请先打出一张，再继续摸打');if(state.replacementPending)throw Error('请先补摸一张，再继续操作');
 if(type==='exposed'&&phase.stage!=='draw')throw Error('明杠须在待摸牌时，用手中三张加别人打出的一张');
 if(type!=='exposed'&&phase.stage!=='discard')throw Error('暗杠或补杠须在摸牌后、打牌前操作');
 const hand=[...state.hand],melds=state.melds.map(m=>[...m]);
 if(type==='added'){const i=melds.findIndex(m=>m.length===3&&m.every(x=>x===t));if(i<0)throw Error('没有对应的碰牌，不能补杠');if(hand[t]<1)throw Error('手中须有一张同牌才能补杠');hand[t]--;melds[i]=Array(4).fill(t);}
 else {const n=type==='concealed'?4:3;if(hand[t]<n)throw Error(type==='concealed'?'暗杠须手中有四张同牌':'明杠须手中有三张同牌');hand[t]-=n;melds.push(Array(4).fill(t));}
 const error=M.validate(hand,melds);if(error)throw Error(error);if(hand.reduce((a,b)=>a+b,0)!==13-3*melds.length)throw Error('手牌数量不符，请先检查手牌与副露');
 return {hand,melds,drawnTile:null,replacementPending:true,claimDiscardPending:false};
}
function applyKongAction(type,t){let next;try{next=planKong(type,t);}catch(e){$('meld-error').textContent=e.message;return false;}
 rememberHand();Object.assign(state,next);handMode=({concealed:'暗杠',exposed:'明杠',added:'补杠'}[type])+' '+M.labels[t]+' · 请补摸一张';$('meld-error').textContent='';persist();renderHand();return true;
}
function planClaim(type,t,start){
 const phase=handPhase();if(!['pong','chi'].includes(type))throw Error('请选择吃或碰');if(!Number.isInteger(t)||t<0||t>27)throw Error('请选择别人打出的牌');
 if(phase.error)throw Error(phase.error);if(phase.stage!=='draw'||state.claimDiscardPending)throw Error(state.replacementPending?'杠后请先补摸一张':'吃碰须在待摸牌时操作；已有多出的一张请先打出');
 if(state.melds.length>=4)throw Error('副露最多四组');
 let meld,take;if(type==='pong'){meld=[t,t,t];take=[t,t];}else{if(t===27)throw Error('红中不能作为顺子中的替代牌来吃');if(!Number.isInteger(start)||start<0||start>=27||start%9>6||Math.floor(start/9)!==Math.floor(t/9)||t<start||t>start+2)throw Error('请选择包含外来牌的同花色顺子');meld=[start,start+1,start+2];take=meld.filter(x=>x!==t);}
 const hand=[...state.hand];for(const x of take){if(hand[x]<1)throw Error('手中缺少 '+M.labels[x]+'，不能用红中代替吃碰');hand[x]--;}
 const melds=[...state.melds.map(m=>[...m]),meld],error=M.validate(hand,melds);if(error)throw Error(error);if(hand.reduce((a,b)=>a+b,0)!==14-3*melds.length)throw Error('手牌数量不符，请检查手牌与副露');
 return {hand,melds,drawnTile:null,replacementPending:false,claimDiscardPending:true};
}
function legalChiCandidates(t){if(!Number.isInteger(t)||t<0||t>=27)return [];const suit=Math.floor(t/9)*9,result=[];for(let start=Math.max(suit,t-2);start<=Math.min(t,suit+6);start++){try{planClaim('chi',t,start);result.push(start);}catch{}}return result;}
function applyClaimAction(type,t,start){let next;try{next=planClaim(type,t,start);}catch(e){$('meld-error').textContent=e.message;return false;}
 rememberHand();Object.assign(state,next);handMode=(type==='pong'?'碰 ':'吃 ')+M.labels[t]+' · 已扣手中两张，请打出一张';$('meld-error').textContent='';persist();renderHand();return true;
}
function renderMeldControls(){const type=$('meld-type').value,t=Number($('meld-base').value),claim=['pong','chi'].includes(type),phase=handPhase();$('meld-base-label').textContent=claim?'别人打出的牌':'副露用牌 / 顺子首张';$('meld-help').textContent=type==='chi'?'确认来自上家的打牌；红框为外来牌，点选要吃的顺子。应用不记录座位顺序。':type==='pong'?'从手中扣两张同牌，加别人打出的一张，碰后直接打牌。':['concealed','exposed','added'].includes(type)?'暗杠扣四张；明杠扣三张；补杠扣一张并升级已有碰牌。杠后先补摸。':'仅补录已经在桌上的副露；手牌中不应含这些牌。';
 const box=$('chi-options');box.replaceChildren();box.hidden=type!=='chi';$('add-meld').hidden=type==='chi';$('add-meld').textContent=type==='pong'?'确认碰牌':'确认录入';$('add-meld').disabled=phase.stage==='replacement'||state.claimDiscardPending||(claim&&phase.stage!=='draw');
 if(type!=='chi')return;const candidates=legalChiCandidates(t);if(!candidates.length){const p=document.createElement('p');p.className='hint';p.textContent=phase.stage!=='draw'?'请先完成当前摸打，再吃牌':t===27?'红中不参与顺子吃牌':'当前没有可吃的顺子；需要两张实际手牌，且不能超过四张同牌';box.append(p);return;}
 for(const start of candidates){const sequence=[start,start+1,start+2],take=sequence.filter(x=>x!==t),b=document.createElement('button');b.type='button';b.className='chi-candidate';b.dataset.start=String(start);b.setAttribute('aria-label','吃 '+sequence.map(x=>M.labels[x]).join('、')+'；外来 '+M.labels[t]+'，扣手中 '+take.map(x=>M.labels[x]).join('、'));const faces=document.createElement('span');faces.className='chi-faces';for(const x of sequence){const img=document.createElement('img');img.src='tiles/'+x+'.svg';img.alt=M.labels[x]+(x===t?'（外来）':'（手中）');if(x===t)img.className='external-tile';faces.append(img);}const text=document.createElement('span');text.textContent='吃这组 · 扣 '+take.map(x=>M.labels[x]).join('、');b.append(faces,text);b.onclick=()=>applyClaimAction('chi',t,start);box.append(b);}
}
function buildPicker(){const picker=$('picker');picker.replaceChildren();M.labels.forEach((_,t)=>{const b=tile(t,()=>applyTileAction('add',t));b.classList.add('picker-tile');picker.append(b);});}
function renderDetailedAnalysis(){const result=$('analysis');result.replaceChildren();const phase=handPhase(),strong=document.createElement('strong');result.append(strong);if(phase.error){strong.textContent=phase.error;return;}if(phase.stage==='replacement'){strong.textContent='杠已录入，请先补摸一张；补摸后再看胡牌与弃牌提示。';return;}if(phase.count===phase.ready){const waiting=M.waits(state.hand,state.melds);strong.textContent=waiting.length?'已听牌 · 自摸以下牌可成胡':'当前未听牌';draws(result,waiting);}else if(phase.count===phase.full){strong.textContent=state.claimDiscardPending?'吃碰后请先打出一张':M.win(state.hand,state.melds)?'结构可胡 · 仅限自摸':'摸牌后暂未成胡';const options=M.discards(state.hand,state.melds);options.forEach(o=>{const p=document.createElement('p');p.textContent='弃 '+M.labels[o.tile]+' → 听 '+o.draws.map(t=>M.labels[t]).join('、');result.append(p);});if(!options.length){const p=document.createElement('p');p.textContent='本次没有一弃即听的选择。';result.append(p);}}else strong.textContent='完整录入手牌后显示胡牌与听牌详情。';}
function renderHand(){const phase=handPhase(),h=$('hand-tiles');h.replaceChildren();const shown=[...state.hand],separate=phase.stage==='discard'&&Number.isInteger(state.drawnTile)&&shown[state.drawnTile]>0;if(separate)shown[state.drawnTile]--;
 shown.forEach((n,t)=>{for(let i=0;i<n;i++)h.append(tile(t,()=>applyTileAction('remove',t)));});
 if(separate){const b=tile(state.drawnTile,()=>applyTileAction('remove',state.drawnTile));b.classList.add('just-drawn');b.setAttribute('aria-label',M.labels[state.drawnTile]+'，新摸入，点击打出');const mark=document.createElement('span');mark.className='drawn-note';mark.textContent='新';b.append(mark);h.append(b);}
 if(phase.stage==='replacement')for(const b of h.children){b.disabled=true;b.setAttribute('aria-label',M.labels[Number(b.dataset.tile)]+'，等待杠后补摸');}
 if(!h.children.length){const empty=document.createElement('p');empty.className='hand-empty';empty.textContent='先点下方牌面，连续录入手牌';h.append(empty);}
 $('hand-count').textContent=phase.count+' / '+phase.full+' 张';$('hand-phase').textContent=phase.error|| (phase.stage==='entry'?'还需录入 '+(phase.ready-phase.count)+' 张':phase.stage==='replacement'?'杠已录入 · 先点下方补摸一张':phase.stage==='draw'?'轮到摸牌 · 点下方加入一张':phase.stage==='discard'?(state.claimDiscardPending?'吃碰已录入 · 直接打出一张':'轮到打牌 · 点手牌打出一张'):'请移除多出的手牌，或检查副露');
 $('hand-mode').textContent=handMode||('副露 '+state.melds.length+' 组 · 手牌仅保存在本机');$('undo-hand').disabled=!handUndo.length;$('hand-workbench').dataset.phase=phase.stage;
 const totals=[...state.hand];state.melds.flat().forEach(t=>totals[t]++);for(const b of $('picker').children){const t=Number(b.dataset.tile);b.disabled=totals[t]>=4||phase.count>=phase.full||!!phase.error;b.setAttribute('aria-label','加入 '+M.labels[t]+'，已用 '+totals[t]+' 张');}
 $('picker-label').textContent=phase.stage==='replacement'?'杠后补摸 · 点牌加入一张':phase.stage==='discard'?(state.claimDiscardPending?'吃碰后不摸牌 · 点上方手牌打出':'先点上方手牌打出，再摸下一张'):phase.stage==='entry'?'点牌录入 · 同一张可以连续点':'点牌摸入';
 $('meld-count').textContent=state.melds.length+' 组';$('melds').replaceChildren();state.melds.forEach((m,i)=>{const d=document.createElement('div');d.className='meld-row';const s=document.createElement('span');s.textContent=m.map(t=>M.labels[t]).join(' ');const b=document.createElement('button');b.textContent='移除';b.className='quiet';b.disabled=phase.stage==='replacement'||state.claimDiscardPending;b.onclick=()=>{if(state.replacementPending||state.claimDiscardPending)return;rememberHand();state.melds.splice(i,1);state.drawnTile=null;state.replacementPending=false;state.claimDiscardPending=false;persist();renderHand();};d.append(s,b);$('melds').append(d);});
 renderMeldControls();
 if($('hand-insights').open)renderDetailedAnalysis();scheduleEfficiency();
}
M.labels.forEach((label,t)=>{const o=document.createElement('option');o.value=t;o.textContent=label;$('meld-base').append(o);});
$('add-meld').onclick=()=>{const t=Number($('meld-base').value),type=$('meld-type').value;if(['pong','chi'].includes(type)){if(type==='pong')applyClaimAction(type,t);return;}if(['concealed','exposed','added'].includes(type)){applyKongAction(type,t);return;}if(state.replacementPending||state.claimDiscardPending){$('meld-error').textContent=state.replacementPending?'请先补摸一张':'吃碰后请先打出一张';return;}const m=type==='sequence'?[t,t+1,t+2]:Array(3).fill(t),melds=[...state.melds,m];const error=type==='sequence'&&(t>=27||t%9>6)?'顺子首张只能为一至七':M.validate(state.hand,melds);$('meld-error').textContent=error;if(!error){rememberHand();state.melds=melds;state.drawnTile=null;state.replacementPending=false;state.claimDiscardPending=false;persist();renderHand();}};
$('meld-type').onchange=()=>{$('meld-error').textContent='';renderMeldControls();};$('meld-base').onchange=()=>{$('meld-error').textContent='';renderMeldControls();};
$('clear-hand').onclick=()=>{rememberHand();handMode='手牌已清空，可点撤销恢复';state.hand=Array(28).fill(0);state.melds=[];state.drawnTile=null;state.replacementPending=false;state.claimDiscardPending=false;$('meld-error').textContent='';persist();renderHand();};
const signed=n=>(n>0?'+':'')+M.formatCents(n);
function scoreDraft(){return {base:$('score-base').value,winner:$('score-winner').value,codes:$('score-codes').value,kongs:state.names.map((_,i)=>$('kong-'+i).value)};}
function currentRound(){const d=scoreDraft();if(d.winner==='')throw Error('请选择谁自摸');return M.calculate(d.base,Number(d.winner),d.codes,d.kongs);}
function previewScore(){state.scoreDraft=scoreDraft();persist();const box=$('score-preview');box.replaceChildren();try{const r=currentRound();const lead=document.createElement('strong');lead.textContent=`${state.names[r.winner]} 自摸 · 每位其他玩家出 ${M.formatCents(r.baseCents*(1+r.codes))}`;box.append(lead);state.names.forEach((name,i)=>{const p=document.createElement('p');p.className='score-detail';const title=document.createElement('b');title.textContent=`${name} 净变动 ${signed(r.deltaCents[i])}`;const detail=document.createElement('span');detail.textContent=`自摸 ${signed(r.selfdraw[i])} · 杠 ${signed(r.kong[i])}（${r.kongs[i]} 次）`;p.append(title,detail);box.append(p);});const foot=document.createElement('small');foot.textContent='四家合计 0 · 确认后才记账';box.append(foot);$('save-round').disabled=false;}catch(e){box.textContent=e.message;$('save-round').disabled=true;}}
function winnerOptions(value){const select=$('score-winner');select.replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent='请选择';select.append(empty);state.names.forEach((name,i)=>{const o=document.createElement('option');o.value=i;o.textContent=name;select.append(o);});select.value=value;}
function renderScore(){const scores=M.totalsCents(state.rounds),draft=state.scoreDraft||{base:'1',winner:'',codes:'',kongs:['','','','']};$('round-count').textContent=`已记 ${state.rounds.length} 局`;$('score-base').value=draft.base??'1';$('score-codes').value=draft.codes??'';winnerOptions(draft.winner??'');$('players').replaceChildren();state.names.forEach((name,i)=>{const row=document.createElement('div');row.className='player';const n=document.createElement('input');n.value=name;n.maxLength=12;n.setAttribute('aria-label',`第 ${i+1} 位昵称`);n.onchange=()=>{const selected=$('score-winner').value;state.names[i]=n.value.trim()||['东','南','西','北'][i];n.value=state.names[i];winnerOptions(selected);persist();previewScore();};const p=document.createElement('span');p.className='points';p.textContent=signed(scores[i]);const d=document.createElement('input');d.type='text';d.inputMode='numeric';d.placeholder='0';d.value=draft.kongs?.[i]??'';d.id='kong-'+i;d.setAttribute('aria-label',`第 ${i+1} 位本局杠次数`);d.oninput=previewScore;row.append(n,p,d);$('players').append(row);});$('undo-round').disabled=!state.rounds.length;$('history').replaceChildren();state.rounds.slice(-8).reverse().forEach((r,i)=>{const p=document.createElement('div');p.className='history-row';const title=document.createElement('b');title.textContent=`第 ${state.rounds.length-i} 局`+(Array.isArray(r)?' · 旧版手动记录':` · ${state.names[r.winner]} 自摸`);const details=document.createElement('p');details.textContent=Array.isArray(r)?'保留原始手动增减':`基数 ${M.formatCents(r.baseCents)} · ${r.codes} 码 · 杠：`+r.kongs.map((v,j)=>`${state.names[j]} ${v}`).join('、');const changes=document.createElement('p');const cents=Array.isArray(r)?r.map(v=>v*100):r.deltaCents;changes.textContent=cents.map((v,j)=>`${state.names[j]} ${signed(v)}`).join(' · ');p.append(title,details,changes);$('history').append(p);});previewScore();}
['score-base','score-winner','score-codes'].forEach(id=>$(id).oninput=previewScore);
$('save-round').onclick=()=>{try{const r=currentRound();const next=[...state.rounds,r];M.totalsCents(next);state.rounds=next;state.scoreDraft={base:$('score-base').value,winner:'',codes:'',kongs:['','','','']};persist();renderScore();$('score-error').textContent='本局已记录；下一局奖码和杠次数已归零';}catch(e){$('score-error').textContent=e.message;}};
$('undo-round').onclick=()=>{state.rounds.pop();persist();renderScore();$('score-error').textContent='已撤销上一局';};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});['hand','score'].forEach(id=>$(id).hidden=id!==b.dataset.tab);document.body.dataset.view=b.dataset.tab;updateNavOffset();});
$('clear-all').onclick=()=>{if(!confirm('清空手牌、副露、昵称和所有积分记录？'))return;state=fresh();handUndo.length=0;handMode='';try{localStorage.removeItem(key);}catch{}renderHand();renderScore();$('score-error').textContent='';$('meld-error').textContent='';};
let analysisWorker=null,analysisTimer=null,analysisTimeout=null,analysisId=0;
function scheduleEfficiency(){clearTimeout(analysisTimer);clearTimeout(analysisTimeout);if(analysisWorker){analysisWorker.terminate();analysisWorker=null;}const id=++analysisId,box=$('efficiency'),n=state.hand.reduce((a,b)=>a+b,0),full=14-3*state.melds.length;box.replaceChildren();document.querySelectorAll('#hand-tiles .suggested').forEach(b=>b.classList.remove('suggested'));$('hand-brief').textContent='';if(state.replacementPending){box.textContent='杠后先补摸一张，再分析完整手牌。';$('hand-brief').textContent='补摸后可自摸胡牌，或再选一张打出';return;}if(M.validate(state.hand,state.melds)||![full-1,full].includes(n)){box.textContent='录入完整手牌后显示向听与有效进牌。';$('hand-brief').textContent='录满手牌后，这里显示一句牌效率提示';return;}box.textContent='正在比较牌效率…';$('hand-brief').textContent='正在比较牌效率…';analysisTimer=setTimeout(()=>{try{analysisWorker=new Worker('analysis-worker.js?v=20261001-chi-pong-v1');analysisTimeout=setTimeout(()=>{if(id!==analysisId)return;analysisWorker?.terminate();analysisWorker=null;box.textContent='本次分析超过 4 秒，未给出排序。手牌与胡牌提示仍可使用。';$('hand-brief').textContent='分析超时，仍可继续摸打';},4000);analysisWorker.onerror=()=>{if(id!==analysisId)return;clearTimeout(analysisTimeout);box.textContent='当前浏览器未能运行后台分析。请通过网站或本地 HTTP 打开；胡牌与听牌提示仍可使用。';$('hand-brief').textContent='后台分析暂不可用，仍可继续摸打';analysisWorker?.terminate();analysisWorker=null;};analysisWorker.onmessage=e=>{if(e.data.id!==analysisId)return;clearTimeout(analysisTimeout);analysisWorker.terminate();analysisWorker=null;if(e.data.error){box.textContent='暂无法分析：'+e.data.error;$('hand-brief').textContent='暂无法分析，仍可继续摸打';return;}renderEfficiency(e.data.result,e.data.ms);};analysisWorker.postMessage({id,hand:[...state.hand],melds:state.melds.map(m=>[...m])});}catch{box.textContent='当前浏览器不支持后台分析；胡牌与听牌提示仍可使用。';$('hand-brief').textContent='后台分析暂不可用，仍可继续摸打';}},100);}
function renderEfficiency(result,ms){const best=result.options?.[0];if(result.mode==='draw')$('hand-brief').textContent=(result.shanten===0?'已听牌':result.shanten+' 向听')+' · 有效 '+result.kinds+' 种 / 理论 '+result.copies+' 枚';else if(result.win&&!state.claimDiscardPending)$('hand-brief').textContent='当前结构可自摸胡牌';else if(best){$('hand-brief').textContent='候选打 '+M.labels[best.discard]+' · '+(best.shanten===0?'听牌':best.shanten+' 向听')+' · 理论有效 '+best.copies+' 枚';document.querySelectorAll('#hand-tiles [data-tile="'+best.discard+'"]').forEach(b=>b.classList.add('suggested'));}const box=$('efficiency');box.replaceChildren();const title=document.createElement('strong');title.textContent=result.mode==='draw'?`牌效率 · ${result.shanten===0?'已听牌':result.shanten+' 向听'}`:'弃牌比较 · 按牌效率排序';box.append(title);const explain=document.createElement('p');explain.textContent='向听越低，离标准胡牌越近；0 为听牌。相同向听优先比较理论有效枚数，再比较种类。';box.append(explain);
function details(parent,r){const p=document.createElement('p');p.textContent=`${r.shanten===0?'听牌':r.shanten+' 向听'} · 有效 ${r.kinds} 种 / 理论 ${r.copies} 枚`;parent.append(p);const d=document.createElement('p');d.className='effective-tiles';d.textContent=r.tiles.length?r.tiles.map(x=>`${M.labels[x.tile]} ×${x.remaining}`).join('、'):'本次没有可降低向听的进牌';parent.append(d);}
if(result.mode==='draw')details(box,result);else{if(result.win&&!state.claimDiscardPending){const p=document.createElement('p');p.textContent='当前已符合自摸胡牌结构；以下仅供选择继续摸打时参考。';box.append(p);}result.options.forEach((r,i)=>{const item=document.createElement(i<3?'div':'details');item.className='discard-option';const label=document.createElement(i<3?'b':'summary');label.textContent=`${i===0?'首选候选 · ':''}弃 ${M.labels[r.discard]} · ${r.shanten===0?'听牌':r.shanten+' 向听'} · ${r.copies} 枚`;item.append(label);details(item,r);box.append(item);});}const note=document.createElement('p');note.className='hint';note.textContent=`只按标准结构作数学比较，非整局绝对最优。理论枚数扣除当前手牌、副露及本次建议弃牌，不含未知对手牌、牌河与牌墙；过往弃牌也未跟踪。计算 ${ms}ms。`;box.append(note);}
$('undo-hand').onclick=()=>{const previous=handUndo.pop();if(!previous)return;state.hand=previous.hand;state.melds=previous.melds;state.drawnTile=previous.drawnTile??null;state.replacementPending=previous.replacementPending===true;state.claimDiscardPending=previous.claimDiscardPending===true;$('meld-error').textContent='';handMode='已撤销上一步';persist();renderHand();};
$('hand-insights').ontoggle=()=>{if($('hand-insights').open)renderDetailedAnalysis();};
function updateNavOffset(){document.documentElement.style.setProperty('--app-nav-height',document.querySelector('nav').offsetHeight+'px');const height=document.querySelector('.hand-keyboard').offsetHeight;if(height)document.documentElement.style.setProperty('--hand-keyboard-height',height+'px');}
if(typeof ResizeObserver!=='undefined'){const observer=new ResizeObserver(updateNavOffset);observer.observe(document.querySelector('nav'));observer.observe(document.querySelector('.hand-keyboard'));}document.querySelectorAll('.hand-secondary details').forEach(d=>d.addEventListener('toggle',()=>document.body.classList.toggle('hand-expanded',[...document.querySelectorAll('.hand-secondary details')].some(x=>x.open))));
buildPicker();renderHand();renderScore();updateNavOffset();
