'use strict';
const M=Mahjong,$=id=>document.getElementById(id),key='hongzhong-family-v1';
const fresh=()=>({hand:Array(28).fill(0),melds:[],names:['东','南','西','北'],rounds:[]});let state=fresh();
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&!M.validate(saved.hand,saved.melds)&&saved.names?.length===4&&saved.names.every(n=>typeof n==='string')&&Array.isArray(saved.rounds)&&saved.rounds.every(M.validRound))state=saved;}catch{}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));}catch{$('storage-status').textContent='浏览器未允许保存；当前记录仅在本次页面停留中保留。';}}
const handUndo=[];let handMode='';function rememberHand(){handUndo.push({hand:[...state.hand],melds:state.melds.map(m=>[...m])});if(handUndo.length>50)handUndo.shift();}function tile(t,click){const b=document.createElement('button');b.className='tile '+(t===27?'hong':['wan','tong','tiao'][Math.floor(t/9)]);b.type='button';b.textContent=t===27?'中':String(t%9+1);const s=document.createElement('small');s.textContent=t===27?'红中':['万','筒','条'][Math.floor(t/9)];b.append(s);b.setAttribute('aria-label',M.labels[t]+(click?'，点击移除':''));if(click)b.onclick=click;else {b.disabled=true;b.style.opacity=1;}return b;}
function draws(container,ts){const d=document.createElement('div');d.className='tiles';ts.forEach(t=>d.append(tile(t)));container.append(d);}
function renderHand(){const h=$('hand-tiles');h.replaceChildren();state.hand.forEach((n,t)=>{for(let i=0;i<n;i++)h.append(tile(t,()=>{rememberHand();state.hand[t]--;handMode='已打出 '+M.labels[t]+'，下一步可摸一张';persist();renderHand();}));});if(!h.children.length)h.textContent='还没有牌，先录入手牌吧';const count=state.hand.reduce((a,b)=>a+b,0),ready=13-state.melds.length*3,full=ready+1;$('hand-count').textContent=`手牌 ${count} 张 · 副露 ${state.melds.length} 组 · 听牌需 ${ready} 张 / 摸牌后 ${full} 张`;
const result=$('analysis');result.replaceChildren();const strong=document.createElement('strong');result.append(strong);const err=M.validate(state.hand,state.melds);if(err)strong.textContent=err;else if(count===ready){const w=M.waits(state.hand,state.melds);strong.textContent=w.length?'已听牌 · 自摸以下牌可成胡':'当前未听牌';draws(result,w);}else if(count===full){strong.textContent=M.win(state.hand,state.melds)?'结构可胡 · 仅限自摸':'摸牌后手牌 · 暂未成胡';const options=M.discards(state.hand,state.melds);if(options.length){const p=document.createElement('p');p.textContent='可弃牌后听牌（不代表胜率排序）：';result.append(p);options.forEach(o=>{const p=document.createElement('p');p.textContent=`弃 ${M.labels[o.tile]} → 听 ${o.draws.map(t=>M.labels[t]).join('、')}`;result.append(p);});}else{const p=document.createElement('p');p.textContent='本次没有一弃即听的选择。';result.append(p);}}else strong.textContent=count<ready?`再录入 ${ready-count} 张查看听牌`:`请将手牌调整为 ${ready} 或 ${full} 张`;
const picker=$('picker');picker.replaceChildren();const total=[...state.hand];state.melds.flat().forEach(t=>total[t]++);for(let s=0;s<4;s++){const row=document.createElement('div');row.className='suit-row';for(let t=s*9;t<Math.min(s*9+9,28);t++){const b=tile(t);b.disabled=total[t]>=4||count>=full;b.style.opacity='';b.setAttribute('aria-label',`加入 ${M.labels[t]}，已用 ${total[t]} 张`);b.onclick=()=>{rememberHand();state.hand[t]++;handMode='已加入 '+M.labels[t];persist();renderHand();};row.append(b);}picker.append(row);}
$('undo-hand').disabled=!handUndo.length;$('hand-mode').textContent=handMode;scheduleEfficiency();$('meld-count').textContent=`${state.melds.length} 组`;$('melds').replaceChildren();state.melds.forEach((m,i)=>{const d=document.createElement('div');d.className='meld-row';const s=document.createElement('span');s.textContent=m.map(t=>M.labels[t]).join(' ');const b=document.createElement('button');b.textContent='移除';b.className='quiet';b.onclick=()=>{rememberHand();state.melds.splice(i,1);persist();renderHand();};d.append(s,b);$('melds').append(d);});}
M.labels.forEach((label,t)=>{const o=document.createElement('option');o.value=t;o.textContent=label;$('meld-base').append(o);});
$('add-meld').onclick=()=>{const t=Number($('meld-base').value),type=$('meld-type').value;const m=type==='sequence'?[t,t+1,t+2]:Array(type==='kong'?4:3).fill(t);const melds=[...state.melds,m];const error=type==='sequence'&&(t>=27||t%9>6)?'顺子首张只能为一至七':M.validate(state.hand,melds);$('meld-error').textContent=error;if(!error){rememberHand();state.melds=melds;persist();renderHand();}};
$('clear-hand').onclick=()=>{rememberHand();handMode='手牌已清空，可撤销';state.hand=Array(28).fill(0);state.melds=[];persist();renderHand();};
const signed=n=>(n>0?'+':'')+M.formatCents(n);
function scoreDraft(){return {base:$('score-base').value,winner:$('score-winner').value,codes:$('score-codes').value,kongs:state.names.map((_,i)=>$('kong-'+i).value)};}
function currentRound(){const d=scoreDraft();if(d.winner==='')throw Error('请选择谁自摸');return M.calculate(d.base,Number(d.winner),d.codes,d.kongs);}
function previewScore(){state.scoreDraft=scoreDraft();persist();const box=$('score-preview');box.replaceChildren();try{const r=currentRound();const lead=document.createElement('strong');lead.textContent=`${state.names[r.winner]} 自摸 · 每位其他玩家出 ${M.formatCents(r.baseCents*(1+r.codes))}`;box.append(lead);state.names.forEach((name,i)=>{const p=document.createElement('p');p.className='score-detail';const title=document.createElement('b');title.textContent=`${name} 净变动 ${signed(r.deltaCents[i])}`;const detail=document.createElement('span');detail.textContent=`自摸 ${signed(r.selfdraw[i])} · 杠 ${signed(r.kong[i])}（${r.kongs[i]} 次）`;p.append(title,detail);box.append(p);});const foot=document.createElement('small');foot.textContent='四家合计 0 · 确认后才记账';box.append(foot);$('save-round').disabled=false;}catch(e){box.textContent=e.message;$('save-round').disabled=true;}}
function winnerOptions(value){const select=$('score-winner');select.replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent='请选择';select.append(empty);state.names.forEach((name,i)=>{const o=document.createElement('option');o.value=i;o.textContent=name;select.append(o);});select.value=value;}
function renderScore(){const scores=M.totalsCents(state.rounds),draft=state.scoreDraft||{base:'1',winner:'',codes:'',kongs:['','','','']};$('round-count').textContent=`已记 ${state.rounds.length} 局`;$('score-base').value=draft.base??'1';$('score-codes').value=draft.codes??'';winnerOptions(draft.winner??'');$('players').replaceChildren();state.names.forEach((name,i)=>{const row=document.createElement('div');row.className='player';const n=document.createElement('input');n.value=name;n.maxLength=12;n.setAttribute('aria-label',`第 ${i+1} 位昵称`);n.onchange=()=>{const selected=$('score-winner').value;state.names[i]=n.value.trim()||['东','南','西','北'][i];n.value=state.names[i];winnerOptions(selected);persist();previewScore();};const p=document.createElement('span');p.className='points';p.textContent=signed(scores[i]);const d=document.createElement('input');d.type='text';d.inputMode='numeric';d.placeholder='0';d.value=draft.kongs?.[i]??'';d.id='kong-'+i;d.setAttribute('aria-label',`第 ${i+1} 位本局杠次数`);d.oninput=previewScore;row.append(n,p,d);$('players').append(row);});$('undo-round').disabled=!state.rounds.length;$('history').replaceChildren();state.rounds.slice(-8).reverse().forEach((r,i)=>{const p=document.createElement('div');p.className='history-row';const title=document.createElement('b');title.textContent=`第 ${state.rounds.length-i} 局`+(Array.isArray(r)?' · 旧版手动记录':` · ${state.names[r.winner]} 自摸`);const details=document.createElement('p');details.textContent=Array.isArray(r)?'保留原始手动增减':`基数 ${M.formatCents(r.baseCents)} · ${r.codes} 码 · 杠：`+r.kongs.map((v,j)=>`${state.names[j]} ${v}`).join('、');const changes=document.createElement('p');const cents=Array.isArray(r)?r.map(v=>v*100):r.deltaCents;changes.textContent=cents.map((v,j)=>`${state.names[j]} ${signed(v)}`).join(' · ');p.append(title,details,changes);$('history').append(p);});previewScore();}
['score-base','score-winner','score-codes'].forEach(id=>$(id).oninput=previewScore);
$('save-round').onclick=()=>{try{const r=currentRound();const next=[...state.rounds,r];M.totalsCents(next);state.rounds=next;state.scoreDraft={base:$('score-base').value,winner:'',codes:'',kongs:['','','','']};persist();renderScore();$('score-error').textContent='本局已记录；下一局奖码和杠次数已归零';}catch(e){$('score-error').textContent=e.message;}};
$('undo-round').onclick=()=>{state.rounds.pop();persist();renderScore();$('score-error').textContent='已撤销上一局';};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});['hand','score'].forEach(id=>$(id).hidden=id!==b.dataset.tab);});
$('clear-all').onclick=()=>{if(!confirm('清空手牌、副露、昵称和所有积分记录？'))return;state=fresh();handUndo.length=0;handMode='';try{localStorage.removeItem(key);}catch{}renderHand();renderScore();$('score-error').textContent='';$('meld-error').textContent='';};
let analysisWorker=null,analysisTimer=null,analysisTimeout=null,analysisId=0;
function scheduleEfficiency(){clearTimeout(analysisTimer);clearTimeout(analysisTimeout);if(analysisWorker){analysisWorker.terminate();analysisWorker=null;}const id=++analysisId,box=$('efficiency'),n=state.hand.reduce((a,b)=>a+b,0),full=14-3*state.melds.length;box.replaceChildren();if(M.validate(state.hand,state.melds)||![full-1,full].includes(n)){box.textContent='录入完整手牌后显示向听与有效进牌。';return;}box.textContent='正在比较牌效率…';analysisTimer=setTimeout(()=>{try{analysisWorker=new Worker('analysis-worker.js?v=20261001-room-compact-v1');analysisTimeout=setTimeout(()=>{if(id!==analysisId)return;analysisWorker?.terminate();analysisWorker=null;box.textContent='本次分析超过 4 秒，未给出排序。手牌与胡牌提示仍可使用。';},4000);analysisWorker.onerror=()=>{clearTimeout(analysisTimeout);box.textContent='当前浏览器未能运行后台分析。请通过网站或本地 HTTP 打开；胡牌与听牌提示仍可使用。';analysisWorker?.terminate();analysisWorker=null;};analysisWorker.onmessage=e=>{if(e.data.id!==analysisId)return;clearTimeout(analysisTimeout);analysisWorker.terminate();analysisWorker=null;if(e.data.error){box.textContent='暂无法分析：'+e.data.error;return;}renderEfficiency(e.data.result,e.data.ms);};analysisWorker.postMessage({id,hand:[...state.hand],melds:state.melds.map(m=>[...m])});}catch{box.textContent='当前浏览器不支持后台分析；胡牌与听牌提示仍可使用。';}},100);}
function renderEfficiency(result,ms){const box=$('efficiency');box.replaceChildren();const title=document.createElement('strong');title.textContent=result.mode==='draw'?`牌效率 · ${result.shanten===0?'已听牌':result.shanten+' 向听'}`:'弃牌比较 · 按牌效率排序';box.append(title);const explain=document.createElement('p');explain.textContent='向听越低，离标准胡牌越近；0 为听牌。相同向听优先比较理论有效枚数，再比较种类。';box.append(explain);
function details(parent,r){const p=document.createElement('p');p.textContent=`${r.shanten===0?'听牌':r.shanten+' 向听'} · 有效 ${r.kinds} 种 / 理论 ${r.copies} 枚`;parent.append(p);const d=document.createElement('p');d.className='effective-tiles';d.textContent=r.tiles.length?r.tiles.map(x=>`${M.labels[x.tile]} ×${x.remaining}`).join('、'):'本次没有可降低向听的进牌';parent.append(d);}
if(result.mode==='draw')details(box,result);else{if(result.win){const p=document.createElement('p');p.textContent='当前已符合自摸胡牌结构；以下仅供选择继续摸打时参考。';box.append(p);}result.options.forEach((r,i)=>{const item=document.createElement(i<3?'div':'details');item.className='discard-option';const label=document.createElement(i<3?'b':'summary');label.textContent=`${i===0?'首选候选 · ':''}弃 ${M.labels[r.discard]} · ${r.shanten===0?'听牌':r.shanten+' 向听'} · ${r.copies} 枚`;item.append(label);details(item,r);box.append(item);});}const note=document.createElement('p');note.className='hint';note.textContent=`只按标准结构作数学比较，非整局绝对最优。理论枚数扣除当前手牌、副露及本次建议弃牌，不含未知对手牌、牌河与牌墙；过往弃牌也未跟踪。计算 ${ms}ms。`;box.append(note);}
$('draw-mode').onclick=()=>{const n=state.hand.reduce((a,b)=>a+b,0),full=14-3*state.melds.length;handMode=n>=full?'请先点手中一张牌打出，再摸牌':'请点下方牌选择器，加入摸到的牌';$('hand-mode').textContent=handMode;$('picker').scrollIntoView({block:'nearest',behavior:'smooth'});};
$('discard-mode').onclick=()=>{handMode='请点手中的一张牌打出';$('hand-mode').textContent=handMode;$('hand-tiles').scrollIntoView({block:'nearest',behavior:'smooth'});};
$('undo-hand').onclick=()=>{const previous=handUndo.pop();if(!previous)return;state.hand=previous.hand;state.melds=previous.melds;handMode='已撤销上一步手牌操作';persist();renderHand();};
renderHand();renderScore();
