(function(root){'use strict';
const M=typeof module!=='undefined'?require('./engine.js'):root.Mahjong;
// Distance to a legal standard winning structure. Maximise retained natural tiles;
// held wildcards fill unmatched structure positions. At most four structural
// positions may require wildcards because a natural tile's physical capacity is 4.
const patterns=[];for(let m=0;m<=4;m++){patterns[m]=[[],[]];const seen=[new Set(),new Set()];const counts=Array(9).fill(0);function emit(){for(let p=0;p<=1;p++)for(let rank=0;rank<(p?9:1);rank++){if(p)counts[rank]+=2;const key=counts.join(',');if(!seen[p].has(key)){seen[p].add(key);patterns[m][p].push([...counts]);}if(p)counts[rank]-=2;}}
function generate(start,left){if(!left){emit();return;}for(let type=start;type<16;type++){const tiles=type<9?[type,type,type]:[type-9,type-8,type-7];tiles.forEach(i=>counts[i]++);generate(type,left-1);tiles.forEach(i=>counts[i]--);}}generate(0,m);}
const suitCache=new Map(),distanceCache=new Map();let evaluations=0;
function suitOptions(c,exposed,max){const key=c.join('')+':'+exposed.join('')+':'+max;if(suitCache.has(key))return suitCache.get(key);const out=[];for(let m=0;m<=max;m++){out[m]=[];for(let p=0;p<=1;p++){const best=Array(5).fill(-100);for(const pattern of patterns[m][p]){let matched=0,requiredWild=0;for(let i=0;i<9;i++){matched+=Math.min(c[i],pattern[i]);requiredWild+=Math.max(0,pattern[i]-(4-exposed[i]));}if(requiredWild<=4)best[requiredWild]=Math.max(best[requiredWild],matched);}out[m][p]=best;}}suitCache.set(key,out);return out;}
function shanten(hand,melds=[]){const error=M.validate(hand,melds);if(error)throw Error(error);const n=hand.reduce((a,b)=>a+b,0),size=14-3*melds.length;if(n!==size&&n!==size-1)throw Error(`需 ${size-1} 或 ${size} 张手牌`);const exposed=Array(28).fill(0);melds.flat().forEach(t=>exposed[t]++);const key=hand.join('')+':'+exposed.join('')+':'+melds.length;if(distanceCache.has(key))return distanceCache.get(key);evaluations++;const required=4-melds.length;let dp=new Map([['0,0,0',0]]);for(let s=0;s<3;s++){const options=suitOptions(hand.slice(s*9,s*9+9),exposed.slice(s*9,s*9+9),required);const next=new Map();for(const [key,matched] of dp){const [m,p,w]=key.split(',').map(Number);for(let add=0;add<=required-m;add++)for(let pair=0;pair<=1-p;pair++)for(let wild=0;wild<=4-exposed[27]-w;wild++){const value=options[add][pair][wild];if(value<0)continue;const k=[m+add,p+pair,w+wild].join(',');next.set(k,Math.max(next.get(k)??-100,matched+value));}}dp=next;}let best=-100;for(let w=0;w<=4-exposed[27];w++)best=Math.max(best,dp.get([required,1,w].join(','))??-100);if(best<0)throw Error('无法形成合法标准结构');const value=Math.max(-1,size-best-hand[27]-1);distanceCache.set(key,value);return value;}
function improving(hand,melds=[]){const s=shanten(hand,melds),used=[...hand];melds.flat().forEach(t=>used[t]++);const tiles=[];for(let t=0;t<28;t++){if(used[t]>=4)continue;const h=[...hand];h[t]++;if(shanten(h,melds)<s)tiles.push({tile:t,remaining:4-used[t]});}return {shanten:s,tiles,kinds:tiles.length,copies:tiles.reduce((a,t)=>a+t.remaining,0)};}
function analyze(hand,melds=[]){const size=14-3*melds.length,n=hand.reduce((a,b)=>a+b,0);if(n===size-1)return {mode:'draw',...improving(hand,melds)};if(n!==size)throw Error(`需 ${size-1} 或 ${size} 张手牌`);const options=[];hand.forEach((v,t)=>{if(!v)return;const h=[...hand];h[t]--;const result=improving(h,melds); // The discarded tile is known unavailable for this next draw.
const draw=result.tiles.find(x=>x.tile===t);if(draw){draw.remaining--;if(draw.remaining===0)result.tiles=result.tiles.filter(x=>x!==draw);result.kinds=result.tiles.length;result.copies=result.tiles.reduce((a,x)=>a+x.remaining,0);}options.push({discard:t,...result});});options.sort((a,b)=>a.shanten-b.shanten||b.copies-a.copies||b.kinds-a.kinds||a.discard-b.discard);return {mode:'discard',win:M.win(hand,melds),options};}
const api={shanten,improving,analyze,stats:()=>({evaluations,suitCache:suitCache.size,distanceCache:distanceCache.size})};if(typeof module!=='undefined')module.exports=api;else root.Efficiency=api;
})(globalThis);
